"""
OCR Watcher 类型存根文件
"""

from typing import List, Dict, Callable, Optional, Tuple
from abc import ABC
from dataclasses import dataclass

@dataclass
class OcrResult:
    """OCR识别结果"""
    text: str
    bbox: Tuple[int, int, int, int]
    confidence: float
    center: Tuple[float, float]
    points: List[Tuple[int, int]]

class OcrEngine(ABC):
    def recognize(self, image_bytes: bytes) -> List[OcrResult]: ...
    def set_confidence_threshold(self, threshold: float) -> None: ...

class AirtestOcrEngine(OcrEngine):
    def __init__(self, lang: str = 'ch', use_gpu: bool = False) -> None: ...

class DeviceController(ABC):
    def screenshot(self) -> bytes: ...
    def click(self, x: int, y: int) -> None: ...
    def press_back(self) -> None: ...

class AirtestDevice(DeviceController):
    def __init__(self) -> None: ...

class TextWatcher:
    _parent: "OcrWatcher"
    _keywords: List[str]
    _match_mode: str
    _region: Optional[Tuple[int, int, int, int]]
    _confidence: Optional[float]
    _cooldown: float
    _last_triggered: float

    def when(self, text: str) -> "TextWatcher": ...
    def match_mode(self, mode: str) -> "TextWatcher": ...
    def region(self, x1: int, y1: int, x2: int, y2: int) -> "TextWatcher": ...
    def confidence(self, threshold: float) -> "TextWatcher": ...
    def cooldown(self, seconds: float) -> "TextWatcher": ...
    def call(self, callback: Callable[[OcrResult, DeviceController], None]) -> "TextWatcher": ...
    def click(self) -> "TextWatcher": ...
    def dismiss(self) -> "TextWatcher": ...

class OcrWatcher:
    _device: DeviceController
    _ocr: OcrEngine
    _watchers: List[Dict]
    _lock: object
    _stop_event: object
    _watch_thread: Optional[object]
    _running: bool
    logger: object

    def __init__(self, device: Optional[DeviceController] = None, ocr_engine: Optional[OcrEngine] = None) -> None: ...
    def when(self, text: str) -> TextWatcher: ...
    def start(self, interval: float = 1.0) -> None: ...
    def stop(self) -> None: ...
    def _watch_forever(self, interval: float) -> None: ...
    def _check_once(self) -> None: ...
    def _match_rule(self, rule: Dict, ocr_results: List[OcrResult]) -> Optional[OcrResult]: ...
    def _text_match(self, text: str, keyword: str, mode: str) -> bool: ...
    def _in_region(self, bbox: Tuple, region: Tuple) -> bool: ...
    def clear(self) -> None: ...
    def set_confidence_threshold(self, threshold: float) -> None: ...

# 全局实例
ocr_watcher: OcrWatcher